CREATE TABLE `crm_receivable` (
  `id` bigint NOT NULL COMMENT '回款ID',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户ID',
  `customer_id` bigint NOT NULL COMMENT '客户ID',
  `contract_id` bigint DEFAULT NULL COMMENT '合同ID',
  `receivable_no` varchar(100) DEFAULT NULL COMMENT '回款编号',
  `amount` decimal(15,2) DEFAULT NULL COMMENT '回款金额',
  `return_date` date DEFAULT NULL COMMENT '回款日期',
  `pay_type` varchar(50) DEFAULT NULL COMMENT '支付方式 (支付宝, 微信, 银行转账, 现金等)',
  `owner_user_id` bigint DEFAULT NULL COMMENT '负责人ID',
  `process_instance_id` varchar(64) DEFAULT NULL COMMENT '工作流实例ID',
  `audit_status` varchar(20) DEFAULT 'DRAFT' COMMENT '审核状态 (DRAFT:草稿, AUDITING:审批中, APPROVED:已通过, REJECTED:已驳回)',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` int DEFAULT '0' COMMENT '删除标志',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='回款表';
