CREATE TABLE `crm_contract` (
  `id` bigint NOT NULL COMMENT '合同ID',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户ID',
  `customer_id` bigint NOT NULL COMMENT '客户ID',
  `opportunity_id` bigint DEFAULT NULL COMMENT '商机ID',
  `name` varchar(255) NOT NULL COMMENT '合同名称',
  `contract_no` varchar(100) DEFAULT NULL COMMENT '合同编号',
  `total_amount` decimal(15,2) DEFAULT NULL COMMENT '合同总金额',
  `sign_date` date DEFAULT NULL COMMENT '签约日期',
  `start_date` date DEFAULT NULL COMMENT '开始日期',
  `end_date` date DEFAULT NULL COMMENT '结束日期',
  `owner_user_id` bigint DEFAULT NULL COMMENT '负责人ID',
  `process_instance_id` varchar(64) DEFAULT NULL COMMENT '工作流实例ID',
  `audit_status` varchar(20) DEFAULT 'DRAFT' COMMENT '审核状态 (DRAFT:草稿, AUDITING:审批中, APPROVED:已通过, REJECTED:已驳回)',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` int DEFAULT '0' COMMENT '删除标志',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='合同表';
