server:
  port: 9203

spring:
  application:
    name: size-workflow
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        import-check:
          enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 请替换为您本地的 MySQL 配置
    url: jdbc:mysql://127.0.0.1:3306/size_crm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: linsz99@

# Flowable 7.2 配置
flowable:
  # 首次启动自动建表，建好后改回 true 即可
  database-schema-update: true
  # 自动部署 processes/ 目录下的所有 .bpmn20.xml 文件
  check-process-definitions: true
  # 关闭 flowable 自带的身份认证 (我们用 sa-token)
  idm-enabled: false
  # 关闭定时任务调度器 (按需开启)
  async-executor-activate: false
